// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//B Munezero Ami christian
//2401000232
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3g8jGPWT3o08pBQRpUd0P9XakMS6vvE',
    appId: '1:292080649020:web:7e9980a4d40620a01ed439',
    messagingSenderId: '292080649020',
    projectId: 'fitness-tracker-5259e',
    authDomain: 'fitness-tracker-5259e.firebaseapp.com',
    storageBucket: 'fitness-tracker-5259e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUQVjIqL2aQK9umUXP_cKVGJGA-iqnes',
    appId: '1:292080649020:android:5961cb96554f1a201ed439',
    messagingSenderId: '292080649020',
    projectId: 'fitness-tracker-5259e',
    storageBucket: 'fitness-tracker-5259e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAgJIBUAIxbU7BASNiv9P_dK192c0dlg',
    appId: '1:292080649020:ios:fdf0b34887bf1a231ed439',
    messagingSenderId: '292080649020',
    projectId: 'fitness-tracker-5259e',
    storageBucket: 'fitness-tracker-5259e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAgJIBUAIxbU7BASNiv9P_dK192c0dlg',
    appId: '1:292080649020:ios:fdf0b34887bf1a231ed439',
    messagingSenderId: '292080649020',
    projectId: 'fitness-tracker-5259e',
    storageBucket: 'fitness-tracker-5259e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3g8jGPWT3o08pBQRpUd0P9XakMS6vvE',
    appId: '1:292080649020:web:64ca6e8d4ad2b1c11ed439',
    messagingSenderId: '292080649020',
    projectId: 'fitness-tracker-5259e',
    authDomain: 'fitness-tracker-5259e.firebaseapp.com',
    storageBucket: 'fitness-tracker-5259e.firebasestorage.app',
  );
}
